# Generated by Django 5.0.2 on 2025-04-15 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='descricao',
            new_name='custo',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='preco',
        ),
        migrations.AddField(
            model_name='produtos',
            name='Margem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produtos',
            name='produto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produtos',
            name='qtd_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='produtos',
            name='venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='EstoqueCategoria',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('nome_categoria', models.CharField(max_length=100)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.produtos')),
            ],
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
