# Generated by Django 5.0.2 on 2025-04-22 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_rename_descricao_produtos_custo_remove_produtos_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoquecategoria',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.produtos'),
        ),
    ]
