# Generated by Django 5.0.2 on 2025-04-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_alter_produtos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoquecategoria',
            name='id',
            field=models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='custo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='qtd',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
