# Generated by Django 5.0.2 on 2025-04-22 16:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_alter_estoquecategoria_id_alter_produtos_custo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoquecategoria',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
