# Generated by Django 5.0.2 on 2025-04-22 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0006_alter_estoquecategoria_id_alter_produtos_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estoquecategoria',
            name='produto',
        ),
        migrations.AddField(
            model_name='produtos',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.estoquecategoria'),
        ),
    ]
