# Generated by Django 5.0.2 on 2025-04-28 20:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_remove_estoquecategoria_produto_produtos_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qtd', models.IntegerField(blank=True, default=0, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('Entrada', 'Entrada'), ('Saída', 'Saída'), ('Devolução', 'Devolução')], max_length=20, null=True)),
                ('motivo', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estoque.produtos')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
            },
        ),
    ]
