# Generated by Django 5.0.2 on 2025-05-07 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_movimentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='estoque.produtos'),
            preserve_default=False,
        ),
    ]
