# Generated by Django 5.0.2 on 2025-10-02 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0011_alter_produtos_custo'),
        ('produto', '0007_alter_lote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='empreendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.empreendimento'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lote', to='produto.lote'),
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='quadra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produto.quadra'),
        ),
    ]
