# Generated by Django 5.0.2 on 2025-10-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0012_movimentacao_empreendimento_movimentacao_lote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='Margem',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='venda',
        ),
        migrations.AlterField(
            model_name='produtos',
            name='qtd_min',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
