# Generated by Django 5.0.2 on 2025-12-05 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0013_remove_produtos_margem_remove_produtos_venda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacao',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='movimentacao',
            name='qtd',
        ),
        migrations.CreateModel(
            name='MovimentacaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(blank=True, default=0, null=True)),
                ('movimentacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.movimentacao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_itens', to='estoque.produtos')),
            ],
        ),
    ]
