# Generated by Django 5.0.2 on 2025-12-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_core_empres_nome_1a6585_idx_and_more'),
        ('estoque', '0015_estoquecategoria_empresa_movimentacao_empresa_and_more'),
        ('produto', '0013_alter_lote_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['empresa', 'created_at'], name='estoque_mov_empresa_b0154a_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['empresa', 'tipo'], name='estoque_mov_empresa_8a5469_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['empreendimento'], name='estoque_mov_empreen_83a229_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['quadra'], name='estoque_mov_quadra__323f41_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['lote'], name='estoque_mov_lote_id_01a232_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['empresa', 'visualizado'], name='estoque_not_empresa_96aa43_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['empresa', 'data_criacao'], name='estoque_not_empresa_2a8b7c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['produto'], name='estoque_not_produto_3a4a25_idx'),
        ),
        migrations.AddIndex(
            model_name='produtos',
            index=models.Index(fields=['empresa', 'produto'], name='estoque_pro_empresa_c6cde2_idx'),
        ),
        migrations.AddIndex(
            model_name='produtos',
            index=models.Index(fields=['empresa', 'categoria'], name='estoque_pro_empresa_1b3d60_idx'),
        ),
        migrations.AddIndex(
            model_name='produtos',
            index=models.Index(fields=['empresa', 'created_at'], name='estoque_pro_empresa_5aa275_idx'),
        ),
        migrations.AddIndex(
            model_name='produtos',
            index=models.Index(fields=['empresa', 'qtd'], name='estoque_pro_empresa_32665e_idx'),
        ),
        migrations.AddIndex(
            model_name='produtos',
            index=models.Index(fields=['categoria'], name='estoque_pro_categor_02e3a8_idx'),
        ),
    ]
