# Generated by Django 5.0.2 on 2025-12-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['nome'], name='core_empres_nome_1a6585_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['cnpj'], name='core_empres_cnpj_70d9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['created_at'], name='core_empres_created_87d066_idx'),
        ),
    ]
