# Generated by Django 5.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_core_empres_nome_1a6585_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='data_vencimento_mensalidade',
            field=models.DateField(blank=True, help_text='Data em que a mensalidade vence', null=True, verbose_name='Data de Vencimento da Mensalidade'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='mensalidade_ativa',
            field=models.BooleanField(default=True, help_text='Indica se a mensalidade está ativa', verbose_name='Mensalidade Ativa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='mensalidade_valor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor mensal da assinatura', max_digits=10, null=True, verbose_name='Valor da Mensalidade'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='mensalidade_dia_vencimento',
            field=models.IntegerField(blank=True, help_text='Dia do mês para vencimento (1-31)', null=True, verbose_name='Dia do Vencimento'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['data_vencimento_mensalidade'], name='core_empres_data_ve_a1b2c3_idx'),
        ),
    ]
