# Generated by Django 5.0.2 on 2025-12-18 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_empresa_mensalidade_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='empresa',
            new_name='core_empres_data_ve_c7751d_idx',
            old_name='core_empres_data_ve_a1b2c3_idx',
        ),
    ]
