# Generated by Django 5.0.2 on 2026-01-23 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_core_empres_data_ve_a1b2c3_idx_core_empres_data_ve_c7751d_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacoesGeral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mensagem', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('visualizado', models.BooleanField(default=False)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_geral', to='core.empresa')),
            ],
            options={
                'verbose_name': 'Notificação Geral',
                'verbose_name_plural': 'Notificações Gerais',
                'indexes': [models.Index(fields=['empresa'], name='core_notifi_empresa_1791e9_idx'), models.Index(fields=['visualizado'], name='core_notifi_visuali_f48ef9_idx'), models.Index(fields=['criado_em'], name='core_notifi_criado__bbc70c_idx')],
            },
        ),
    ]
