# Generated by Django 5.0.2 on 2024-05-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cnpj_cpf',
            new_name='cpf_cnpj',
        ),
    ]
