# Generated by Django 5.0.2 on 2024-09-11 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_alter_cliente_cep_alter_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
