# Generated by Django 5.0.2 on 2025-12-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_cliente_empresa'),
        ('core', '0002_empresa_core_empres_nome_1a6585_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'nome_completo'], name='cliente_cli_empresa_66ffa4_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'cpf_cnpj'], name='cliente_cli_empresa_324ff3_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'email'], name='cliente_cli_empresa_683c73_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['empresa', 'data_cadastro'], name='cliente_cli_empresa_8dc669_idx'),
        ),
    ]
