# Generated by Django 5.0.2 on 2026-04-08 19:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0006_cliente_cliente_cli_empresa_66ffa4_idx_and_more'),
        ('core', '0005_notificacoesgeral'),
        ('produto', '0016_alter_lote_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id_venda', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_venda', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_venda', models.CharField(choices=[('Pendente', 'Pendente'), ('Concluída', 'Concluída'), ('Cancelada', 'Cancelada')], default='Pendente', max_length=10)),
                ('quitado', models.BooleanField(default=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('id_lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.lote')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Cartão de Crédito', 'Cartão de Crédito'), ('Pix', 'Pix'), ('Boleto', 'Boleto'), ('Transferência', 'Transferência')], max_length=20)),
                ('data_pagamento', models.DateField(default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa')),
                ('id_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.vendas')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_pagamento'],
            },
        ),
        migrations.AddIndex(
            model_name='vendas',
            index=models.Index(fields=['empresa', 'status_venda'], name='vendas_vend_empresa_7f72ed_idx'),
        ),
        migrations.AddIndex(
            model_name='vendas',
            index=models.Index(fields=['empresa', 'create_at'], name='vendas_vend_empresa_c4c9b6_idx'),
        ),
    ]
