# Generated by Django 5.0.2 on 2024-05-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
