# Generated by Django 5.0.2 on 2024-05-27 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_users_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cargo',
            field=models.CharField(choices=[('A', 'Administrador'), ('V', 'Vendedor'), ('G', 'Gerente')], default='V', max_length=1),
        ),
    ]
