# Generated by Django 5.0.2 on 2025-07-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_users_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cargo',
            field=models.CharField(choices=[('A', 'Administrador'), ('V', 'Vendedor'), ('G', 'Gerente'), ('E', 'Estoquista')], default='V', max_length=1),
        ),
    ]
