# Generated by Django 5.0.2 on 2024-07-09 14:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='empreendimentos')),
                ('nome', models.CharField(max_length=255)),
                ('localizacao', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Empreendimento',
                'verbose_name_plural': 'Empreendimentos',
            },
        ),
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('metragem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lotes', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.empreendimento')),
            ],
            options={
                'verbose_name': 'Quadra',
                'verbose_name_plural': 'Quadras',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('metragem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('proprietario', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.quadra')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
    ]
