# Generated by Django 5.0.2 on 2025-04-28 20:35

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0004_alter_cliente_cpf_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empreendimento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='empreendimentos/')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('localizacao', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Empreendimento',
                'verbose_name_plural': 'Empreendimentos',
            },
        ),
        migrations.CreateModel(
            name='Quadra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='quadras/')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('metragem', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.empreendimento')),
            ],
            options={
                'verbose_name': 'Quadra',
                'verbose_name_plural': 'Quadras',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('numero', models.IntegerField(auto_created=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metragem', models.CharField(max_length=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_aquisicao', models.DateField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0), null=True)),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('R', 'Reservado'), ('V', 'Vendido')], default=True, max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('proprietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Lotes', to='cliente.cliente')),
                ('quadra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.quadra')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
    ]
