# Generated by Django 5.0.2 on 2025-04-28 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('D', 'Disponível'), ('V', 'Vendido'), ('R', 'Reservado')], default=True, max_length=1),
        ),
    ]
