# Generated by Django 5.0.2 on 2024-07-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadra',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
