# Generated by Django 5.0.2 on 2024-09-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_quadra_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
