# Generated by Django 5.0.2 on 2024-09-11 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_empreendimento_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quadra',
            name='lotes',
        ),
    ]
