# Generated by Django 5.0.2 on 2024-09-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_remove_quadra_lotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadra',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='quadras'),
        ),
    ]
