# Generated by Django 5.0.2 on 2024-09-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_quadra_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='empreendimentos/'),
        ),
        migrations.AlterField(
            model_name='quadra',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='quadras/'),
        ),
    ]
