# Generated by Django 5.0.2 on 2025-07-10 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_lote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('R', 'Reservado'), ('D', 'Disponível'), ('V', 'Vendido')], default=True, max_length=1),
        ),
    ]
