# Generated by Django 5.0.2 on 2024-09-27 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_empreendimento_foto_alter_quadra_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empreendimento',
            old_name='foto',
            new_name='imagem',
        ),
    ]
