# Generated by Django 5.0.2 on 2025-10-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_alter_lote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='imagem',
            field=models.ImageField(blank=True, default='empreendimentos/default.jpg', null=True, upload_to='empreendimentos/'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('V', 'Vendido'), ('D', 'Disponível'), ('R', 'Reservado')], default=True, max_length=1),
        ),
    ]
