# Generated by Django 5.0.2 on 2024-10-16 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_alter_lote_numero_alter_lote_proprietario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='data_aquisicao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('R', 'Reservado'), ('V', 'Vendido'), ('D', 'Disponível')], default=True, max_length=1),
        ),
    ]
