# Generated by Django 5.0.2 on 2025-10-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0008_alter_empreendimento_imagem_alter_lote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='imagem',
            field=models.ImageField(blank=True, default='empreendimentos/default.png', null=True, upload_to='empreendimentos/'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('R', 'Reservado'), ('D', 'Disponível'), ('V', 'Vendido')], default=True, max_length=1),
        ),
    ]
