# Generated by Django 5.0.2 on 2024-10-17 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_cpf_cnpj'),
        ('produto', '0009_lote_data_aquisicao_alter_lote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Lotes', to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('R', 'Reservado'), ('D', 'Disponível'), ('V', 'Vendido')], default=True, max_length=1),
        ),
    ]
