# Generated by Django 5.0.2 on 2025-12-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0009_alter_empreendimento_imagem_alter_lote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('V', 'Vendido'), ('D', 'Disponível'), ('R', 'Reservado')], default=True, max_length=1),
        ),
    ]
