# Generated by Django 5.0.2 on 2025-12-18 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('produto', '0011_lote_empresa_quadra_empresa_alter_lote_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('R', 'Reservado'), ('V', 'Vendido'), ('D', 'Disponível')], default=True, max_length=1),
        ),
    ]
