# Generated by Django 5.0.2 on 2025-12-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_core_empres_nome_1a6585_idx_and_more'),
        ('produto', '0012_empreendimento_empresa_alter_lote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('D', 'Disponível'), ('R', 'Reservado'), ('V', 'Vendido')], default=True, max_length=1),
        ),
        migrations.AddIndex(
            model_name='quadra',
            index=models.Index(fields=['empresa', 'empreendimento'], name='produto_qua_empresa_4ea0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='quadra',
            index=models.Index(fields=['empresa', 'nome'], name='produto_qua_empresa_b66d42_idx'),
        ),
        migrations.AddIndex(
            model_name='quadra',
            index=models.Index(fields=['empreendimento'], name='produto_qua_empreen_1ec371_idx'),
        ),
    ]
