# Generated by Django 5.0.2 on 2024-11-19 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0012_alter_lote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='metragem',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('D', 'Disponível'), ('V', 'Vendido'), ('R', 'Reservado')], default=True, max_length=1),
        ),
    ]
