# Generated by Django 5.0.2 on 2026-01-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0013_alter_lote_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('V', 'Vendido'), ('R', 'Reservado'), ('D', 'Disponível')], default=True, max_length=1),
        ),
    ]
