<<<<<<< HEAD
# Generated by Django 5.0.2 on 2025-04-15 18:37
=======
# Generated by Django 5.0.2 on 2025-03-20 19:14
>>>>>>> 236f6e0a120d571e8116c03b1b879f59c2703846

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0013_alter_lote_metragem_alter_lote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('R', 'Reservado'), ('D', 'Disponível'), ('V', 'Vendido')], default=True, max_length=1),
        ),
    ]
