# Generated by Django 5.0.2 on 2025-04-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0014_alter_lote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('V', 'Vendido'), ('R', 'Reservado'), ('D', 'Disponível')], default=True, max_length=1),
        ),
    ]
