# Generated by Django 5.0.2 on 2026-05-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0016_alter_lote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(choices=[('D', 'Disponível'), ('R', 'Reservado'), ('V', 'Vendido')], default=True, max_length=1),
        ),
    ]
