# Generated by Django 5.2 on 2026-05-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0019_alter_lote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='status',
            field=models.CharField(blank=True, choices=[('Vendido', 'Vendido'), ('Reservado', 'Reservado'), ('Disponivel', 'Disponível')], default=True, max_length=20, null=True),
        ),
    ]
