# Generated by Django 5.0.2 on 2024-03-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('nome_titular', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_emissao', models.DateField()),
                ('data_compensacao', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(blank=True, choices=[('E', 'Emitido'), ('C', 'Compensado'), ('V', 'Vencido'), ('S', 'Sem Fundo'), ('D', 'Devolvido')], default='E', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('D', 'Dinheiro'), ('C', 'Cartão de Crédito'), ('B', 'Boleto'), ('T', 'Transferência Bancária'), ('C', 'Cheque')], default='D', max_length=1, null=True)),
                ('pago', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('recebido', models.BooleanField(default=False)),
                ('forma_recebimento', models.CharField(blank=True, choices=[('D', 'Dinheiro'), ('C', 'Cartão de Crédito'), ('B', 'Boleto'), ('T', 'Transferência Bancária'), ('C', 'Cheque')], default='D', max_length=1, null=True)),
            ],
        ),
    ]
