# Generated by Django 5.0.2 on 2024-03-20 00:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='banco',
            field=models.CharField(blank=True, choices=[('001', 'Banco do Brasil'), ('104', 'Caixa Econômica Federal'), ('237', 'Bradesco'), ('341', 'Itaú'), ('356', 'Santander'), ('033', 'Banco Santander (Brasil)'), ('745', 'Citibank'), ('399', 'HSBC'), ('422', 'Safra'), ('389', 'Mercantil do Brasil'), ('633', 'Rendimento'), ('652', 'Itaú Unibanco Holding'), ('745', 'Banco Citibank'), ('748', 'Sicredi'), ('756', 'Sicoob')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='data_compensacao',
            field=models.DateField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='data_emissao',
            field=models.DateField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='data_pagamento',
            field=models.DateField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='data_vencimento',
            field=models.DateField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('D', 'Dinheiro'), ('C', 'Cartão de Crédito'), ('B', 'Boleto'), ('T', 'Transferência Bancária'), ('C', 'Cheque'), ('P', 'PIX')], default='D', max_length=1, null=True),
        ),
    ]
