# Generated by Django 5.0.2 on 2024-05-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='forma_recebimento',
            field=models.CharField(blank=True, choices=[('D', 'Dinheiro'), ('B', 'Boleto'), ('E', 'Cartão'), ('T', 'Banco'), ('C', 'Cheque'), ('P', 'PIX')], default='D', max_length=1, null=True),
        ),
    ]
