# Generated by Django 5.0.2 on 2024-07-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_alter_contareceber_forma_recebimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='descricao',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='descricao',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
