# Generated by Django 5.0.2 on 2024-08-27 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_alter_contapagar_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contareceber',
            name='data_vencimento',
        ),
    ]
