# Generated by Django 5.0.2 on 2024-04-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_despesascategoria_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
