# Generated by Django 5.0.2 on 2024-08-27 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_remove_contareceber_data_vencimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contapagar',
            name='data_vencimento',
        ),
    ]
