# Generated by Django 5.0.2 on 2024-09-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_remove_contapagar_data_vencimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('D', 'Dinheiro'), ('B', 'Boleto'), ('T', 'Banco'), ('C', 'Cheque'), ('P', 'PIX'), ('M', 'Dinheiro/Banco'), ('N', 'Cheque/Dinheiro')], default='D', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='forma_recebimento',
            field=models.CharField(blank=True, choices=[('D', 'Dinheiro'), ('B', 'Boleto'), ('E', 'Cartão'), ('T', 'Banco'), ('C', 'Cheque'), ('P', 'PIX'), ('M', 'Dinheiro/Banco'), ('N', 'Cheque/Dinheiro')], default='D', max_length=1, null=True),
        ),
    ]
