# Generated by Django 5.0.2 on 2024-04-30 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_alter_cheque_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='contareceber',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='data_recebimento',
            field=models.DateField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='data_vencimento',
            field=models.DateField(blank=True, default=datetime.datetime(1900, 1, 1, 0, 0), null=True),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='forma_recebimento',
            field=models.CharField(blank=True, choices=[('D', 'Dinheiro'), ('E', 'Cartão de Crédito'), ('B', 'Boleto'), ('T', 'Transferência Bancária'), ('C', 'Cheque')], default='D', max_length=1, null=True),
        ),
    ]
