# Generated by Django 5.0.2 on 2024-04-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_contareceber_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='recebido',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
