# Generated by Django 5.0.2 on 2025-12-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_cliente_cliente_cli_empresa_66ffa4_idx_and_more'),
        ('core', '0002_empresa_core_empres_nome_1a6585_idx_and_more'),
        ('financeiro', '0008_fornecedor_empresa'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['empresa', 'data_recebimento'], name='financeiro__empresa_2e7652_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['empresa', 'recebido'], name='financeiro__empresa_c5673b_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['empresa', 'cliente'], name='financeiro__empresa_ffae49_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['cliente'], name='financeiro__cliente_3de520_idx'),
        ),
    ]
