# Generated by Django 5.0.2 on 2024-05-13 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_rename_cnpj_cpf_cliente_cpf_cnpj'),
        ('financeiro', '0008_alter_contareceber_recebido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despesascategoria',
            old_name='descricao',
            new_name='nome_categoria',
        ),
        migrations.AddField(
            model_name='despesascategoria',
            name='conta_pagar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contapagar'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='nome_titular',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='situacao',
            field=models.CharField(blank=True, choices=[('E', 'Emitido'), ('C', 'Compensado'), ('V', 'Vencido'), ('S', 'Sem Fundo'), ('D', 'Devolvido'), ('R', 'Repassado')], default='E', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.despesascategoria'),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='forma_pagamento',
            field=models.CharField(blank=True, choices=[('D', 'Dinheiro'), ('B', 'Boleto'), ('T', 'Banco'), ('C', 'Cheque'), ('P', 'PIX')], default='D', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contareceber',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.cliente'),
        ),
    ]
