"""
Django settings for imperio project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'usuarios',
    'rolepermissions',
    'core',
    'financeiro',
    'cliente',
    'produto',
    'estoque',
    'vendas',
    'notifications',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'usuarios.middleware.MensalidadeMiddleware',  # Middleware de verificação de mensalidade
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'imperio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'estoque.context_processors.notificacoes_context',
                'core.context_processors.empresa_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'imperio.wsgi.application'


# Database
# Railway injeta DATABASE_URL automaticamente; fallback para variáveis individuais (dev local)
_DATABASE_URL = config('DATABASE_URL', default='')

if _DATABASE_URL:
    # Produção (Railway): usa DATABASE_URL — inclui SSL e todas as configs
    DATABASES = {
        'default': dj_database_url.parse(
            _DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Desenvolvimento local: variáveis individuais do .env
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': config('POSTGRES_NAME'),
            'USER': config('POSTGRES_USER'),
            'PASSWORD': config('POSTGRES_PASSWORD'),
            'HOST': config('DB_HOST', default='host.docker.internal'),
            'PORT': config('DB_PORT', default=5432, cast=int),
            'CONN_MAX_AGE': 600,
            'OPTIONS': {
                'connect_timeout': 10,
                'options': '-c statement_timeout=30000',
            }
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ── Armazenamento de arquivos (Cloudflare R2 ou local) ────────────────────────
_R2_BUCKET = config('R2_BUCKET_NAME', default='')

if _R2_BUCKET:
    # Produção: arquivos no Cloudflare R2
    _R2_ACCOUNT_ID = config('R2_ACCOUNT_ID')
    _R2_CUSTOM_DOMAIN = config('R2_CUSTOM_DOMAIN', default='')

    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key":         config('R2_ACCESS_KEY_ID'),
                "secret_key":         config('R2_SECRET_ACCESS_KEY'),
                "bucket_name":        _R2_BUCKET,
                "endpoint_url":       f"https://{_R2_ACCOUNT_ID}.r2.cloudflarestorage.com",
                "region_name":        "auto",
                "default_acl":        None,   # R2 não suporta ACLs
                "file_overwrite":     False,
                "querystring_auth":   True,   # URLs assinadas (acesso privado)
                "querystring_expire": 3600,   # Expiram em 1 hora
                "signature_version":  "s3v4",
            },
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

    # Se tiver domínio personalizado (ex: files.alicerce.com.br), usa ele
    # Se não, aponta pro endpoint R2 direto
    if _R2_CUSTOM_DOMAIN:
        MEDIA_URL = f"https://{_R2_CUSTOM_DOMAIN}/"
    else:
        MEDIA_URL = f"https://{_R2_ACCOUNT_ID}.r2.cloudflarestorage.com/{_R2_BUCKET}/"

    MEDIA_ROOT = None   # Não usado quando R2 está ativo

else:
    # Desenvolvimento: arquivos locais
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# ─────────────────────────────────────────────────────────────────────────────


# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'usuarios.Users'

# Authentication Backends
AUTHENTICATION_BACKENDS = [
    'usuarios.backends.MensalidadeBackend',  # Backend customizado com verificação de mensalidade
]

# Role Permissions
ROLEPERMISSIONS_MODULE = 'imperio.roles'
# settings.py
DEFAULT_CHARSET = 'utf-8'

# Email configuration
EMAIL_BACKEND     = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST        = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT        = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS     = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER   = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL  = config('DEFAULT_FROM_EMAIL', default='Alicerce by Pulsari <noreply@pulsarianalytics.com.br>')

# Login redirect
LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'

# Cache configurations
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Cache middleware
MIDDLEWARE.insert(0, 'django.middleware.cache.UpdateCacheMiddleware')
MIDDLEWARE.append('django.middleware.cache.FetchFromCacheMiddleware')

# Cache settings
CACHE_MIDDLEWARE_ALIAS = 'default'
CACHE_MIDDLEWARE_SECONDS = 3  # 10 minutes
CACHE_MIDDLEWARE_KEY_PREFIX = 'imperio'

# ── Segurança em produção (ativado automaticamente quando DEBUG=False) ────────
if not DEBUG:
    # Railway (e PaaS em geral) faz SSL no proxy — não redirecionar aqui
    # pois causaria loop infinito. Usar SECURE_PROXY_SSL_HEADER no lugar.
    SECURE_SSL_REDIRECT            = False
    SECURE_PROXY_SSL_HEADER        = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE          = True
    CSRF_COOKIE_SECURE             = True
    SECURE_HSTS_SECONDS            = 31536000   # 1 ano
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD            = True
    SECURE_CONTENT_TYPE_NOSNIFF    = True
    SECURE_BROWSER_XSS_FILTER      = True
    X_FRAME_OPTIONS                = 'DENY'
# ─────────────────────────────────────────────────────────────────────────────

